# Generated by Django 6.0.4 on 2026-04-08 20:10

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.CharField(choices=[('L1', 'Level 1'), ('L2', 'Level 2'), ('L3', 'Level 3')], max_length=2),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('review', 'Under Review'), ('approved', 'Approved'), ('published', 'Published')], default='submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='specialization',
            field=models.CharField(choices=[('SE', 'Software Engineering'), ('SR', 'Systems and Networks'), ('GL', 'Genie Logiciel')], default='SR', max_length=2),
        ),
        migrations.AlterField(
            model_name='report',
            name='pdf_file',
            field=models.FileField(upload_to=core.models.report_upload_path),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
