# Generated by Django 6.0.4 on 2026-04-08 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_studentprofile_level_report_status_report_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='center',
            field=models.ForeignKey(blank=True, help_text='Required for center-specific admins.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aicscenter'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='preview_image',
            field=models.FileField(blank=True, help_text='Upload a preview image (FileField used to avoid Pillow dependency).', null=True, upload_to='reports/previews/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='assigned_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_students', to='core.supervisorprofile'),
        ),
    ]
