# Generated by Django 6.0.3 on 2026-04-15 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_center_studentprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Grade over 20.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='report',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='supervisor_feedback',
            field=models.TextField(blank=True),
        ),
    ]
