# Generated by Django 6.0.3 on 2026-05-11 15:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_report_grade_report_graded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pdf_file',
            field=models.FileField(max_length=500, upload_to=core.models.report_upload_path),
        ),
        migrations.AlterField(
            model_name='report',
            name='preview_image',
            field=models.FileField(blank=True, help_text='Upload a preview image (FileField used to avoid Pillow dependency).', max_length=500, null=True, upload_to='reports/previews/'),
        ),
    ]
